##
# settings.py
##

import socket

class SETTINGS(object):
	""" Settings du / des servers """

	# DEBUG CONFIGURATION
	IS_DEBUG = True

	# SERVER CONFIGURATION
	SERVER_PORT = 9999
	SERVER_HTTP_PORT = 81
	#SERVER_HOST = socket.gethostbyname(socket.gethostname())
	SERVER_HOST = 'localhost'

	# CHANNEL/ROOM CONFIGURATION
	CHANNEL_MAX_USERS = 100
	MASTER_PASSWORD = 'admin'

	# THREADS CONFIGURATION
	LOG_QUEUE_NB_THREAD = 4
	WORKER_QUEUE_NB_THREAD = 4

	# WATCHDOG CONFIGURATION
	WATCHDOG_SLEEP_TIME = 10
	WATCHDOG_MAX_IDLE_TIME = 70
